import { useState, type ReactNode } from 'react';
import { ArrowUpRight, Award as AwardIcon, ChevronDown, CircleHelp, Coins, Crosshair, LockKeyhole, Medal, Shield, Trophy } from 'lucide-react';
import type { GameSnapshot, Stage } from '../shared/contracts';
import { coins, date, dateTime, stageLabel } from './lib';
import { EmptyState, TeamMark } from './components';

export function LeaderboardPage({ game }: { game: GameSnapshot }) {
  const [tab, setTab] = useState<'ranking' | 'scorers' | 'awards'>('ranking');
  const scorers = [...game.leaderboard].sort((a, b) => b.scorerHits - a.scorerHits || a.displayName.localeCompare(b.displayName, 'fi'));
  return <div className="leaderboard-page"><div className="page-heading"><div><h1>Porukan pörssi</h1><p>Kisakolikot lasketaan. Kunnia muistetaan.</p></div><Trophy className="heading-emblem" size={38} strokeWidth={1.4} /></div><div className="page-tabs" role="tablist" aria-label="Porukan tilastot">{([{ id: 'ranking', label: 'Sarjataulukko', icon: Trophy }, { id: 'scorers', label: 'Maalipörssi', icon: Crosshair }, { id: 'awards', label: 'Kunnia', icon: Medal }] as const).map(item => <button type="button" role="tab" aria-selected={tab === item.id} aria-controls={`stats-${item.id}`} id={`tab-${item.id}`} tabIndex={tab === item.id ? 0 : -1} key={item.id} onClick={() => setTab(item.id)} onKeyDown={event => { if (event.key === 'ArrowRight' || event.key === 'ArrowLeft') { event.preventDefault(); const ids = ['ranking', 'scorers', 'awards'] as const; const next = ids[(ids.indexOf(tab) + (event.key === 'ArrowRight' ? 1 : 2)) % 3]; setTab(next); document.getElementById(`tab-${next}`)?.focus(); } }}><item.icon size={17} />{item.label}</button>)}</div>
    {tab === 'ranking' && <section role="tabpanel" id="stats-ranking" aria-labelledby="tab-ranking"><div className="ranking-intro"><p>Järjestys perustuu kokonaisvarallisuuteen: oma kassa + avoimien vetojen omalla rahalla rahoitettu panos.</p><span>Päiväbonus ei nosta sijoitusta.</span></div>{game.leaderboard.length === 0 ? <EmptyState title="Pörssi odottaa pelaajia." icon={<Trophy size={30} />}><p>Sijoitukset tulevat näkyviin pelaajatietojen päivittyessä.</p></EmptyState> : <div className="ranking-board"><div className="ranking-column-labels"><span>Pelaaja</span><span>Voitot / ohi</span><span>Yhteensä</span></div>{game.leaderboard.map(player => <article key={player.userId} className={`ranking-row ${player.userId === game.user.id ? 'is-me' : ''} ${player.rank === 1 ? 'is-leader' : ''}`}><div className="rank-number">{player.rank === 1 ? <Trophy size={25} strokeWidth={1.6} aria-label="Ensimmäinen" /> : player.rank}</div><div className="ranking-player"><h2>{player.displayName}{player.userId === game.user.id && <span className="you-label">Sinä</span>}</h2><p>Kassassa {coins(player.bankroll)}<span> · </span>Vedoissa {coins(player.openStake)}</p><div className="recent-form" aria-label="Viimeisimmät vetotulokset">{player.recent.slice(0, 5).map((result, index) => <span key={index} className={result} title={result === 'won' ? 'Voitto' : result === 'lost' ? 'Ohi' : 'Palautettu'} aria-label={result === 'won' ? 'Voitto' : result === 'lost' ? 'Ohi' : 'Palautettu'}>{result === 'won' ? 'V' : result === 'lost' ? 'O' : 'P'}</span>)}{player.recent.length === 0 && <span className="no-results">Ei vielä ratkaistuja vetoja</span>}</div></div><div className="ranking-record"><strong>{player.won}<span> / {player.lost}</span></strong><small>{player.settledNet > 0 ? '+' : ''}{coins(player.settledNet)} netto</small></div><div className="ranking-total"><strong>{coins(player.total)}</strong><span>kolikkoa</span></div></article>)}</div>}<div className="round-note"><Coins size={17} /><p>Avoin veto siirtyy tuloksen ratketessa voitoksi tai tappioksi. Lopullinen kassa ratkaisee kauden voittajan.</p></div></section>}
    {tab === 'scorers' && <section role="tabpanel" id="stats-scorers" aria-labelledby="tab-scorers"><div className="section-intro"><h2>Maalivainu ratkaisee.</h2><p>Osuneet maalintekijävedot. Yksi voittanut veto on yksi osuma, vaikka pelaaja tekisi hattutempun.</p></div><div className="scorer-board">{scorers.map((player, index) => <div className={`scorer-row ${player.userId === game.user.id ? 'is-me' : ''}`} key={player.userId}><span className="scorer-rank">{player.scorerHits > 0 ? scorers.findIndex(item => item.scorerHits === player.scorerHits) + 1 : '–'}</span><span className="avatar">{player.displayName.slice(0, 1)}</span><strong>{player.displayName}</strong><div><strong>{player.scorerHits}</strong><span>{player.scorerHits === 1 ? 'osuma' : 'osumaa'}</span></div></div>)}</div>{scorers.every(player => player.scorerHits === 0) && <p className="quiet-note">Ensimmäistä osumaa odotellaan. Maalipörssi herää otteluiden mukana.</p>}</section>}
    {tab === 'awards' && <section role="tabpanel" id="stats-awards" aria-labelledby="tab-awards"><div className="section-intro"><h2>Kentän laidalla muistetaan.</h2><p>Kauden teot, onnistumiset ja porukan puheenaiheet.</p></div>{game.awards.length === 0 ? <EmptyState title="Kunnia ansaitaan kentällä." icon={<Medal size={30} />}><p>Kauden palkinnot muodostuvat ratkaistuista vedoista.</p></EmptyState> : <div className="awards-list">{game.awards.map((award, index) => <article className={`award-row ${award.playerName ? 'awarded' : ''}`} key={award.id}><div className="award-symbol">{index % 3 === 0 ? <Trophy size={30} strokeWidth={1.4} /> : index % 3 === 1 ? <Medal size={30} strokeWidth={1.4} /> : <AwardIcon size={30} strokeWidth={1.4} />}</div><div><h3>{award.title}</h3><p>{award.description}</p><strong>{award.playerName ?? 'Vielä vailla omistajaa'}</strong></div><span className="award-value">{award.value}</span></article>)}</div>}</section>}
  </div>;
}

export function ChampionsLeaguePage({ game }: { game: GameSnapshot }) {
  const [tab, setTab] = useState<'table' | 'ties'>('table');
  const stages: Stage[] = ['playoff', 'round_of_16', 'quarter_final', 'semi_final', 'final'];
  return <div className="uefa-page"><div className="page-heading"><div><h1>Kilpailu</h1><p>36 seuraa. Yksi yhteinen liigavaihe. Tie finaaliin.</p></div><Shield className="heading-emblem" size={38} strokeWidth={1.4} /></div><div className="filter-group section-filter" aria-label="Kilpailun näkymä"><button type="button" aria-pressed={tab === 'table'} onClick={() => setTab('table')}>Liigataulukko</button><button type="button" aria-pressed={tab === 'ties'} onClick={() => setTab('ties')}>Pudotuspelit</button></div>
    {tab === 'table' && <><div className="qualification-legend"><span><i className="direct" />1–8 · Suoraan jatkoon</span><span><i className="playoff" />9–24 · Karsintaan</span><span><i />25–36 · Ulkona</span></div>{game.standings.length === 0 ? <EmptyState title="Liigataulukko päivittyy pian." icon={<Shield size={30} />}><p>Seurojen sijoitukset tulevat ottelutietojen mukana. Oman porukan liiga alkaa toiselta kierrokselta, mutta UEFA-taulukko sisältää koko liigavaiheen.</p></EmptyState> : <div className="table-scroll" tabIndex={0} role="region" aria-label="Mestarien liigan taulukko, vieritettävissä vaakasuunnassa"><table className="standings-table"><thead><tr><th scope="col"><span className="sr-only">Sija</span>#</th><th scope="col">Seura</th><th scope="col"><abbr title="Ottelut">O</abbr></th><th scope="col"><abbr title="Voitot">V</abbr></th><th scope="col"><abbr title="Tasapelit">T</abbr></th><th scope="col"><abbr title="Tappiot">H</abbr></th><th scope="col">Maalit</th><th scope="col"><abbr title="Maaliero">ME</abbr></th><th scope="col"><abbr title="Pisteet">P</abbr></th></tr></thead><tbody>{[...game.standings].sort((a, b) => a.position - b.position).map(standing => <tr key={standing.team.id} className={standing.position === 8 || standing.position === 24 ? 'cutoff-row' : ''}><td><span className={`standing-position ${standing.position <= 8 ? 'direct' : standing.position <= 24 ? 'playoff' : ''}`}>{standing.position}</span></td><th scope="row"><span><TeamMark team={standing.team} small />{standing.team.shortName || standing.team.name}</span></th><td>{standing.played}</td><td>{standing.won}</td><td>{standing.drawn}</td><td>{standing.lost}</td><td>{standing.goalsFor}–{standing.goalsAgainst}</td><td>{standing.goalsFor - standing.goalsAgainst > 0 ? '+' : ''}{standing.goalsFor - standing.goalsAgainst}</td><td><strong>{standing.points}</strong></td></tr>)}</tbody></table></div>}<p className="quiet-note">Taulukko perustuu vahvistettuihin tuloksiin ja sisältää myös ennen oman pelimme alkua pelatut ottelut. Käsin ylläpidetty järjestys käyttää pisteitä, maalieroa ja tehtyjä maaleja; tasatilanteissa sija on jaettu. UEFA:n täydelliset tasapistesäännöt voivat muuttaa lopullista sijoitusta.</p></>}
    {tab === 'ties' && <>{game.ties.length === 0 ? <EmptyState title="Pudotuspelipaikat ovat vielä jaossa." icon={<Trophy size={30} />}><p>Otteluparit ilmestyvät tänne, kun ne vahvistetaan. Näet molemmat osaottelut, yhteismaalit ja jatkoonmenijän samasta paikasta.</p></EmptyState> : <div className="tie-stages">{stages.map(stage => {
      const ties = game.ties.filter(tie => tie.stage === stage);
      return ties.length > 0 && <section className="tie-stage" key={stage}><h2>{stageLabel[stage]}</h2><div className="tie-grid">{ties.map(tie => <article className="tie-card" key={tie.id}><div className="tie-meta"><span>{stage === 'final' ? 'Yksi ottelu' : 'Kaksi osaottelua'}</span><span>{stage === 'final' ? 'Tulos' : 'Yhteismaalit'}</span></div>{[tie.homeTeam, tie.awayTeam].map((team, index) => <div className={`tie-team ${tie.advancingTeamId === team.id ? 'advancing' : ''}`} key={team.id}><TeamMark team={team} small /><strong>{team.shortName}</strong>{tie.advancingTeamId === team.id && <ArrowUpRight size={16} aria-label={stage === 'final' ? 'Voittaja' : 'Jatkoon'} />}<span>{(index === 0 ? tie.homeAggregate : tie.awayAggregate) ?? '–'}</span></div>)}<div className="tie-result">{tie.advancingTeamId ? `${tie.advancingTeamId === tie.homeTeam.id ? tie.homeTeam.shortName : tie.awayTeam.shortName} ${stage === 'final' ? 'voitti' : 'jatkoon'}` : 'Ottelupari ratkaisematta'}</div>{tie.legs.map(match => <p className="tie-leg" key={match.id}>{match.leg ? `${match.leg}. osa · ` : ''}{dateTime(match.kickoffAtUtc)}<br />{match.homeTeam.shortName || match.homeTeam.name} – {match.awayTeam.shortName || match.awayTeam.name}{match.homeScoreFinal !== null && match.awayScoreFinal !== null && (match.homeScoreFinal !== match.homeScore || match.awayScoreFinal !== match.awayScore) ? ` · ${match.homeScoreFinal}–${match.awayScoreFinal} jatkoajan jälkeen · 90 min ${match.homeScore}–${match.awayScore}` : match.homeScore !== null && match.awayScore !== null ? ` · ${match.homeScore}–${match.awayScore} (90 min)` : match.status === 'postponed' ? ' · Siirretty' : match.status === 'cancelled' ? ' · Peruttu' : ''}</p>)}</article>)}</div></section>;
    })}</div>}<div className="round-note"><CircleHelp size={17} /><p>1X2 ja tarkka tulos ratkaistaan kunkin osaottelun 90 minuutin tuloksesta. Jatkoonmenijä ratkaistaan otteluparin yhteistuloksesta. Vierasmaalisääntöä ei ole.</p></div></>}
  </div>;
}

export function RulesPage({ game, onChangePin }: { game: GameSnapshot; onChangePin: () => void }) {
  const config = game.season.config;
  return <div className="rules-page"><div className="page-heading"><div><h1>Oman porukan pelikirja</h1><p>Tutut kisakolikot, uusi eurooppalainen kausi.</p></div><CircleHelp className="heading-emblem" size={37} strokeWidth={1.4} /></div><div className="rules-start"><div><Trophy size={32} strokeWidth={1.5} /><h2>Kassa ratkaisee.</h2></div><p>Aloituskassa on <strong>{coins(config.startingBalance)} kolikkoa</strong>. Oman porukan liiga alkaa <strong>{date(game.season.gameStartAt)} 2026</strong> toiselta liigakierrokselta. Ensimmäisen kierroksen ottelut eivät kuulu peliin. Kauden lopussa suurin kassa voittaa.</p></div><div className="rules-list">
    <Rule title="Jätä kierroksen vedot nopeasti" open><p>Valitse otteluista 1, X tai 2. <strong>Tarkista vedot</strong> näyttää kaikki valinnat ja yhteisen panoksen, joka on aluksi 20 kolikkoa. Vetoja ei jätetä ennen vahvistusta. Jokainen ottelu on erillinen veto.</p><p>Pienin panos on {coins(config.minimumStake)} kolikkoa. Voit muokata panosta tai perua vedon ennen ottelun alkua. Tarkat tulokset ja maalintekijät löytyvät ottelun <strong>Lisävedot</strong>-painikkeesta.</p></Rule>
    <Rule title="Päiväbonus pitää porukan pelissä" open><p>Jokaiselle peliin kuuluvalle ottelupäivälle saat <strong>{coins(config.dailyBonus)} bonuskolikkoa</strong>. Saman päivän ottelut käyttävät yhteistä bonuspottia. Bonus käytetään ennen omaa kassaa; sitä ei lasketa pörssin varallisuuteen.</p><p>Käyttämätön bonus vanhenee päivän jälkeen. Jos oma vapaa kassa on silloin alle <strong>{coins(config.recoveryThreshold)} kolikkoa</strong>, jäljellä oleva bonus siirtyy kassaan. Bonusta ei saa välipäiviltä. Voit pelata oman tahdin mukaan.</p></Rule>
    <Rule title="Mikä tulos voittaa?"><ul><li><strong>1X2:</strong> 1 on kotivoitto, X tasapeli ja 2 vierasvoitto. Vain 90 minuuttia lisäaikoineen.</li><li><strong>Tarkka tulos:</strong> ottelun maalit 90 minuutin jälkeen. Jatkoaikaa tai rangaistuspotkukilpailua ei lasketa.</li><li><strong>Maalintekijä:</strong> pelaajan on tehtävä maali varsinaisella peliajalla lisäaikoineen. Omaa maalia tai rangaistuspotkukilpailun maalia ei lasketa. Pelaamatta jääneen pelaajan panos palautetaan, kun osallistumistieto on vahvistettu.</li></ul><p>Jos tulos- tai maalintekijätiedoista puuttuu varmistus, veto odottaa selvitystä.</p></Rule>
    <Rule title="Kertoimet ja palautus"><p>Vedon kerroin tallentuu jättöhetkellä. Voittavan vedon palautus on <strong>panos × kerroin</strong>, ja se sisältää panoksen. Myös bonuskolikolla saatu voitto siirtyy omaan kassaan.</p><p>Jos kertoimet ehtivät vaihtua ennen jättämistä, palvelin pyytää tarkistamaan valinnat uudelleen. Merkintä <strong>Kertoimet tulossa</strong> tarkoittaa, ettei kohteeseen voi vielä jättää vetoa.</p></Rule>
    <Rule title="Vedot ovat salassa avauspotkuun"><p>Porukka näkee ennen ottelua vain jätettyjen 1X2-vetojen määrän. Valinnat, panokset ja kertoimet paljastuvat ottelun alkaessa. Omat vedot näkyvät aina itsellesi.</p><p>Kaikki ajat näytetään Suomen aikaa. Vedot lukitaan avauspotkuun palvelimen kellon mukaan.</p></Rule>
    <Rule title="Kaksi osaottelua, yksi jatkoonmenijä"><p>Pudotuspeliparit pelataan kahdessa osassa finaalia lukuun ottamatta. Jokaisesta osaottelusta voi lyödä omat 90 minuutin vetonsa. Pari ratkaistaan yhteismaaleilla; vierasmaalisääntöä ei ole.</p><p>Tasatilanteessa toisen osaottelun jälkeen pelataan jatkoaika ja tarvittaessa rangaistuspotkukilpailu. Niiden maalit eivät vaikuta 90 minuutin vetoihin.</p></Rule>
    <Rule title="Pörssi, maalipörssi ja kunnia"><p>Pörssi laskee yhteen oman kassan ja avoimissa vedoissa olevan omasta kassasta maksetun panoksen. Näin avoin veto ei pudota sijoitusta heti jättämishetkellä. Ratkaistut voitot ja tappiot päivittävät tilannetta.</p><p>Maalipörssi laskee osuneet maalintekijävedot. Kunnia-välilehdellä näkyvät kauden erityiset onnistumiset.</p></Rule>
    <Rule title="Siirretyt ottelut ja korjaukset"><p>Siirretyn ottelun vedot odottavat uutta vahvistettua aikaa tai ylläpitäjän ratkaisua. Perutun ottelun vedot palautetaan. Puutteellisesta tuloksesta ei arvata voittajaa.</p><p>Ylläpitäjä voi korjata virheellisen tuloksen perustelun kanssa. Korjaus oikaisee vedot ja palautukset, ja siitä jää merkintä tapahtumalokiin.</p></Rule>
    <Rule title="PIN ja oma tili"><p>Valitse oma 6–32 numeron PIN. Älä jaa sitä muille. Jos unohdat PINin, pyydä liigan ylläpitäjältä palautusta.</p><button className="button secondary" type="button" onClick={onChangePin}><LockKeyhole size={16} />Vaihda oma PIN</button></Rule>
  </div><p className="rules-closing">Sama porukka. Pidempi kausi. Hyviä jalkapalloiltoja.</p></div>;
}

function Rule({ title, children, open = false }: { title: string; children: ReactNode; open?: boolean }) { return <details className="rule" open={open || undefined}><summary>{title}<ChevronDown size={19} /></summary><div>{children}</div></details>; }
